- src/main/java/com/kakaoseventeen/dogwalking/chat/controller/ChatController.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatService.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatServiceImpl.java
- src/main/java/com/kakaoseventeen/dogwalking/config/WebSocketConfig.java
- Configuration
- Controller Layer
- DTO
- Service 기본 틀
- 테스트코드는 구현 완료 후 작성할 계획입니다.
- API문서는 구현 완료 후 수정될 수 있습니다.
- Repository & Entity는 다음 PR에 올리겠습니다.
close #16
> Chat Config, Controller Impl

- .gitignore
- .idea/workspace.xml
- src/main/java/com/kakaoseventeen/dogwalking/walkRoad/domain/WalkRoad.java
- WalkRoad 엔티티 구현 및 주석 작성
- 전반적인 주석 작성 통일하기 및 위, 경도를 더 잘 표현할 수 있는 타입 및 방법을 찾아보기
close #23
> WalkRoad 엔티티 구현 

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/CursorRequest.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/controller/HomeRestController.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/controller/NotificationRestController.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/domain/Notification.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/dto/request/UpdateNotificationDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/service/HomeService.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/service/NotificationService.java
- /home 컨트롤러, 서비스 틀 작성
- 공고글 수정 로직 수정 및 추가
> 작업내용들 BE_2 브랜치로 PR

- src/main/java/com/kakaoseventeen/dogwalking/notification/controller/HomeRestController.java
- src/test/java/com/kakaoseventeen/dogwalking/notification/service/NotificationServiceTest.java
> 6주차 작업내용 pr

- src/main/java/com/kakaoseventeen/dogwalking/review/domain/Review.java
> Review Entity 구현

- src/main/java/com/kakaoseventeen/dogwalking/application/domain/Application.java
- src/main/java/com/kakaoseventeen/dogwalking/review/domain/Review.java
- Application Entity 구현
close #62
> 지원서 Entity 구현

- src/main/java/com/kakaoseventeen/dogwalking/match/domain/Match.java
> 매칭 Entity 구현

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GetEntity.java
- src/main/java/com/kakaoseventeen/dogwalking/application/domain/Application.java
- src/main/java/com/kakaoseventeen/dogwalking/application/repository/ApplicationRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/match/domain/Match.java
- src/main/java/com/kakaoseventeen/dogwalking/match/repository/MatchingRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/controller/WalkController.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- src/test/java/com/kakaoseventeen/dogwalking/dog/DogControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/member/MemberControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walk/WalkRespTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walk/WalkRestControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walk/WalkServiceTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walkRoad/WalkRoadControllerTest.java
- 산책 시작하기 기능 변경사항 적용 및 테스트 코드 수정
close #71
> 산책 시작하기 기능 변경사항 적용

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GetEntity.java
- src/main/java/com/kakaoseventeen/dogwalking/payment/PaymentService.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/controller/WalkController.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- src/test/java/com/kakaoseventeen/dogwalking/dog/DogControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/member/MemberControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walk/WalkRestControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walk/WalkServiceTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walkRoad/WalkRoadControllerTest.java
- 산책 종료하기 기능 변경사항 적용 및 통합 테스트 충돌 해결
close #72
> 산책 종료하기 기능 변경사항 적용

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ApiResponseGenerator.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GetEntity.java
- src/main/java/com/kakaoseventeen/dogwalking/member/domain/Member.java
- src/main/java/com/kakaoseventeen/dogwalking/payment/controller/PaymentController.java
- src/main/java/com/kakaoseventeen/dogwalking/payment/domain/Payment.java
- src/main/java/com/kakaoseventeen/dogwalking/payment/service/PaymentService.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- src/test/java/com/kakaoseventeen/dogwalking/payment/PaymentControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walk/WalkRestControllerTest.java
- 산책하기 기능 구현 및 통합 테스트 완료
close #74
> 산책하기 기능 구현 및 통합 테스트 완료

- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/IsOwnerRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- 본인의 프로필인지 분기 처리하는 API 구현
close #75
> 본인의 프로필인지 분기 처리하는 API 구현

- build.gradle
- src/main/java/com/kakaoseventeen/dogwalking/application/repository/ApplicationRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/review/repository/ReviewRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- src/main/java/com/kakaoseventeen/dogwalking/walkRoad/dto/WalkRoadRespDTO.java
- 프로필 상세 조회  구현
추후 통합 테스트 예정
close #30
> 프로필 조회  구현

- build.gradle
- src/main/java/com/kakaoseventeen/dogwalking/chat/controller/ChatRoomController.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/domain/ChatMessage.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/domain/ChatRoom.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/domain/MessageType.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatRoomReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/repository/ChatMessageRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/repository/ChatRoomRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatMessageWriteServiceImpl.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomWriteService.java
- src/main/java/com/kakaoseventeen/dogwalking/config/WebSocketConfig.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/domain/Dog.java
- src/main/java/com/kakaoseventeen/dogwalking/member/domain/Member.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/domain/Notification.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/domain/Walk.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- src/main/java/com/kakaoseventeen/dogwalking/walkRoad/domain/WalkRoad.java
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatmessage/integration/WebSocketTest.java
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/controller/ChatRoomControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomWriteServiceTest.java
- src/test/java/com/kakaoseventeen/dogwalking/payment/PaymentRespTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walk/WalkRespTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walk/WalkRestControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walk/WalkServiceTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walkRoad/WalkRoadControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walkRoad/WalkRoadRepsTest.java
- src/test/java/com/kakaoseventeen/dogwalking/walkRoad/WalkRoadServiceTest.java
- 채팅방 생성
- 채팅 리팩토링
- 채팅 통합 테스트 코드 작성
- build gradle 수정
- 폴더 명 model에서 domain으로 변경
close #69
> 채팅 테스트 및 리팩토링

- Dockerfile
- build.gradle
- src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- walkEnd(산책 종료) API Spec에 receiverId 추가
close #87
> walkEnd API Spec에 receiverId 추가

- src/main/resources/application-prod.yml
- Prod 환경에 맞는 Profile의 yml 코드 작성
close #101
> Prod 환경에서 yml 코드 작성

- src/main/java/com/kakaoseventeen/dogwalking/member/domain/Member.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/controller/InitController.java
- src/main/java/com/kakaoseventeen/dogwalking/walkRoad/service/WalkRoadService.java
- src/main/resources/application-prod.yml
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatmessage/integration/WebSocketTest.java
- walk, walkRoad, application, match init data 생성 API 수정
close #106
> walk, walkRoad, application, match init data 생성 API 수정

- src/main/java/com/kakaoseventeen/dogwalking/notification/controller/InitController.java
- src/main/java/com/kakaoseventeen/dogwalking/payment/service/PaymentService.java
- Payment Service 내 기본키 중복 예외처리 추가
close #108
> Payment Service 내 기본키 중복 예외처리 추가

- src/main/java/com/kakaoseventeen/dogwalking/notification/domain/Notification.java
- src/main/resources/application-prod.yml
- prod 환경에서 테이블 네이밍 전략 수정
close #113
> prod 환경에서 테이블 네이밍 전략 수정

- src/main/resources/application-prod.yml
- prod 환경에서 yml 코드 중 JPA 설정 변경
close #115
> prod 환경에서 yml 코드 중 JPA 설정 변경

- src/main/resources/application-prod.yml
- application.yml 내 jpa 설정 mariadb 버젼 수정
close #115
> application.yml 내 jpa 설정 mariadb 버젼 수정

- src/main/resources/application-prod.yml
- application.yml 내 jpa 설정 mariadb 종속성 수정
close #115
> application.yml 내 jpa 설정 mariadb 종속성 수정

- src/main/resources/application-prod.yml
- application.yml 내 jpa name 설정 수정
close #115
> application.yml 내 jpa name 설정 수정

- src/main/resources/application-prod.yml
- application.yml 내 jpa 설정 수정
close #115
> application.yml 내 jpa 설정 수정

- src/main/java/com/kakaoseventeen/dogwalking/notification/domain/Notification.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
- Notification 엔티티 및 Repository 쿼리 수정
close #115
> Notification 엔티티 및 Repository 쿼리 수정

- src/main/java/com/kakaoseventeen/dogwalking/notification/controller/InitController.java
- initController 수정
close #이슈번호
> fix : initController 수정

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/MemberMessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/MessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/controller/WalkController.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatmessage/integration/WebSocketTest.java
…보내주는 방식으로 변경
- 프로필 조회 API에서 url Path 변수인 userId가 null이면 JWT 인가된 유저 프로필 본인의 정보를 반환하는 방식으로 변경
close #127
> 프로필 조회 API에서 url Path 변수인 userId가 null이면 JWT 인가된 유저 프로필 본인의 정보를 반환하는 방식으로 변경

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/SecurityConfig.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/MessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/CoinNotEnoughException.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/DogListNotExistException.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/NotificationUpdateException.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/service/NotificationService.java
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatmessage/integration/WebSocketTest.java
- src/test/java/com/kakaoseventeen/dogwalking/notification/controller/NotificationControllerTest.java
- 공고글 예외처리 관련 수정
- 테스트코드 작성
close #이슈번호
> 공고글 예외처리 관련 수정

- build.gradle
- src/main/java/com/kakaoseventeen/dogwalking/member/service/Validator.java
- src/test/java/com/kakaoseventeen/dogwalking/member/valid/ValidatorTest.java
- 비밀번호 길이 검증 로직 수정
- 테스트 코드 작성
closes #132
> 비밀번호 길이 검증 로직 수정

- src/main/java/com/kakaoseventeen/dogwalking/member/service/Validator.java
- src/test/java/com/kakaoseventeen/dogwalking/member/valid/ValidatorTest.java
- 회원가입 비밀번호 패턴 정규식 `#` 특수문자 추가
- 회원가입 비밀번호 패턴 정규식 테스트
closes #134
> 회원가입 비밀번호 패턴 정규식 특수문자 추가

- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- MemberController 중 유저 프로필 조회시 userId 선택적으로 값 받도록 수정
close #137
> 유저 프로필 조회시 userId 선택적으로 값 받도록 수정

- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/test/java/com/kakaoseventeen/dogwalking/member/MemberControllerTest.java
- 유저 프로필 조회시 Pathvariable 유무에 따른 분기 url
close #137
> 유저 프로필 조회시 Pathvariable 유무에 따른 분기 url

- src/main/java/com/kakaoseventeen/dogwalking/application/repository/ApplicationRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/repository/DogJpaRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- 유저 프로필 조회시 DTO 코드 변경
- 각 컬렉션이 empty인지에 따라서 값 반환
close #137
> 유저 프로필 조회시 DTO 코드 변경

- src/main/java/com/kakaoseventeen/dogwalking/dog/repository/DogJpaRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/service/NotificationService.java
- notification으로 User 조회 쿼리 네이밍 쿼리에서 JPQL 쿼리로 수정
close #137
> notification으로 User 조회 쿼리 네이밍 쿼리에서 JPQL 쿼리로 수정

- src/main/java/com/kakaoseventeen/dogwalking/dog/repository/DogJpaRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/service/NotificationService.java
- src/test/java/com/kakaoseventeen/dogwalking/member/MemberControllerTest.java
- notification으로 User 조회 쿼리 JPQL 메서드 인자 수정
close #137
> notification으로 User 조회 쿼리 JPQL 메서드 인자 수정

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/JwtAuthenticationFilter.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/security/JwtProvider.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/security/handler/FilterResponse.java
> 토큰 예외처리 이슈 해결 (Feat#104 to weekly)

- src/main/java/com/kakaoseventeen/dogwalking/chat/controller/ChatController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- src/main/java/com/kakaoseventeen/dogwalking/review/repository/ReviewRepository.java
- 멤버 프로필 Profile 조회 중 Review API Spec 변경
close #146
> 멤버 프로필 Profile 조회 중 Review API Spec 변경

- src/main/java/com/kakaoseventeen/dogwalking/dog/controller/DogController.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/service/DogService.java
- src/test/java/com/kakaoseventeen/dogwalking/dog/DogServiceTest.java
- Dog Controller Path Variable 중 UserId에서 @AuthenticationPrinciple로 변경
close #148
> Dog Controller Path Variable 중 UserId에서 @AuthenticationPrinciple로 변경

- src/main/java/com/kakaoseventeen/dogwalking/dog/controller/DogController.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/service/DogService.java
- Dog 프로필 조회시 없는 id 값 받으면 500이 아니라 400 에러 뜨게 핸들링하기
close #150
> Dog 프로필 조회시 없는 id 값 받으면 500이 아니라 400 에러 뜨게 핸들링하기

- src/main/java/com/kakaoseventeen/dogwalking/application/controller/ApplicationController.java
- src/main/java/com/kakaoseventeen/dogwalking/application/domain/Application.java
- src/main/java/com/kakaoseventeen/dogwalking/application/dto/CreateAppReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/application/dto/GetAppResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationReadService.java
- src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationWriteService.java
- src/main/java/com/kakaoseventeen/dogwalking/match/repository/MatchingRepository.java
- 지원서 제목필드추가
- 지원서 상세조회
- 지원서 작성
closes #131
> 지원서 조회, 작성 기능

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/MessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/DuplicateNotificationWithWalkException.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/PaymentNotExistException.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- src/main/java/com/kakaoseventeen/dogwalking/payment/controller/PaymentController.java
- src/main/java/com/kakaoseventeen/dogwalking/payment/service/PaymentService.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/controller/WalkController.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- 산책 허락하기시 공고가 이미 다른 산책과 연결된 경우에 예외처리하기
- 기타 RumtimeException을 커스텀 Exception으로 변경
close #152
> 산책 허락하기시 공고가 이미 다른 산책과 연결된 경우에 예외처리하기

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/FilterResponse.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/security/JwtProvider.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/security/SecurityConfig.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/dto/response/LoadNotificationRespDTO.java
- src/main/resources/application.yml
- 시크릿 키 값 @value속성 추가, 공고글 응답 수정
close #이슈번호
> 시크릿 키 값 @value속성 추가, 공고글 응답 수정(Feat#104 to weekly)

- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/controller/InitController.java
- initController간 Review 목 데이터 추가
close #156
> initController간 Review 목 데이터 추가

- src/main/java/com/kakaoseventeen/dogwalking/notification/controller/InitController.java
- 데이터베이스에 사전 Review Mock 필수값 작성 후 저장
close #158
> 데이터베이스에 사전 Review Mock 필수값 작성 후 저장

- build.gradle
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/S3Config.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/S3Uploader.java
- src/main/resources/application-prod.yml
AWS S3 이미지 업로드 적용
- build.gradle 의존성 추가
- application-prod.yml S3 설정 추가
- S3Config 구현
- S3Uploader 구현
close #160
> AWS S3 이미지 업로드 적용하기

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/MessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/ImageNotExistException.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/controller/DogController.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/domain/Dog.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/dto/DogReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/service/DogService.java
- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/UpdateProfileReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- 기존 이미지 필드 S3 연동 후 실 S3 저장하고, 저장 URL 반환
close #163
> 기존 이미지 필드 S3 연동 후 실 S3 저장하고, 저장 URL 반환

- src/main/java/com/kakaoseventeen/dogwalking/dog/controller/DogController.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/dto/DogReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/service/DogService.java
- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/UpdateProfileReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- 기존 DogController, MemberController 이미지 인자를 @RequestPart로 이미지 파싱하도록 변경
close #163
> @RequestPart로 이미지 파싱하도록 변경

- src/main/java/com/kakaoseventeen/dogwalking/dog/controller/DogController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/UpdateProfileReqDTO.java
- MultiFile과 Json을 한 API에서 둘 다 요청할시 consume을 통해서 직접 미디어 타입 지정해주기
close #163
> consumes 속성을 통해 미디어 타입 직접 지정

- src/main/java/com/kakaoseventeen/dogwalking/dog/controller/DogController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- MemberController, DogController consumes 속성 제거
close #163
> consumes 속성 제거

- src/main/java/com/kakaoseventeen/dogwalking/dog/controller/DogController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- MemberController 프로필 수정 기능 415 Unsupported Media Type 에러 슈팅
close #163
> MemberController 프로필 수정 기능 415 Unsupported Media Type 에러 슈팅

- src/main/java/com/kakaoseventeen/dogwalking/dog/controller/DogController.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/dto/DogReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/UpdateProfileReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- src/test/java/com/kakaoseventeen/dogwalking/dog/DogControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/dog/DogServiceTest.java
- 415 Unsupported Media Type Error ModelAttribute로 트러블 슈팅
close #163
> 415 Unsupported Media Type Error ModelAttribute로 트러블 슈팅

- src/main/java/com/kakaoseventeen/dogwalking/dog/controller/DogController.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/dto/DogReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/UpdateProfileReqDTO.java
- 415 Unsupported Media Type Error ModelAttribute DTO 객체 Builder 선언
close #163
> 415 Unsupported Media Type Error ModelAttribute DTO 객체 Builder 선언

- src/main/java/com/kakaoseventeen/dogwalking/dog/dto/DogReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/UpdateProfileReqDTO.java
- 415 Unsupported Media Type Error ModelAttribute DTO 객체 의존 객체 추가
close #163
> 415 Unsupported Media Type Error ModelAttribute DTO 객체 의존 객체 추가

- src/main/java/com/kakaoseventeen/dogwalking/dog/dto/DogReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/UpdateProfileReqDTO.java
- 415 Unsupported Media Type Error ModelAttribute DTO 객체 Noargs 추가
close #163
> 415 Unsupported Media Type Error ModelAttribute DTO 객체 Noargs 추가

- src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationReadService.java
- src/main/java/com/kakaoseventeen/dogwalking/match/repository/MatchingRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/domain/Notification.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteService.java
- src/test/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteServiceTest.java
> 리뷰 500 에러 수정

- src/main/java/com/kakaoseventeen/dogwalking/chat/controller/ChatRoomController.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatListResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/repository/ChatMessageRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/repository/ChatRoomRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
- src/main/java/com/kakaoseventeen/dogwalking/match/repository/MatchingRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/match/service/MatchService.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/domain/Notification.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
> 채팅목록 조회 기능

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- Member Profile Update간 비영속 상태 객체(@AuthenticationPrinciple CustomUser)를 영속 상태로 전환
close #182
> Member Profile Update간 비영속 상태 객체를 영속 상태로 전환

- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- Profile에서 notification에서 산책완료여부를 판단 할 walkstatus 추가 및 생성자 코드 변경
close #184
> Profile에서 notification에서 산책완료여부를 판단 할 walkstatus 추가

- src/main/java/com/kakaoseventeen/dogwalking/dog/controller/DogController.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/domain/Dog.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/dto/DogUpdateReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/service/DogService.java
- 강아지 프로필 수정 API 구현
- 강아지 프로필 수정 API 구현 및 이에 따른 API 문서 작성 및 수정하기
close #186
> 강아지 프로필 수정 API 구현

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/JwtAuthenticationFilter.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/security/JwtProvider.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/LoginReqDTO.java
- src/main/resources/application.yml
- src/test/java/com/kakaoseventeen/dogwalking/member/MemberControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/notification/controller/HomeControllerTest.java
- 홈 , 로그인 테스트코드 작성, secret key 환경변수 설정
> 홈 , 로그인 테스트코드 작성, secret key 환경변수 설정(Be 2 to weekly)

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/S3Uploader.java
- src/main/resources/application-prod.yml
- JwtProvider @Value 에러 수정
close #191
> JwtProvider @Value 에러 수정

- src/main/java/com/kakaoseventeen/dogwalking/dog/domain/Dog.java
- Dog Request DTO age 필드 타입 Int에서 String으로 수정
close #191
> Dog Request DTO age 필드 타입 수정

- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/domain/Member.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- Member Profile Update 기능 수정
close #195
> Member Profile Update 기능 수정

- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- Member Profile Update 필드 수정
- ProfileContent 필드 추가
close #195
> Member Profile Update 필드 수정

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/ChatRoomMessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatroom/ChatRoomMatchNotFoundException.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatroom/ChatRoomMemberNotFoundException.java
- src/main/java/com/kakaoseventeen/dogwalking/application/controller/ApplicationController.java
- src/main/java/com/kakaoseventeen/dogwalking/application/dto/GetAppResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationReadService.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/domain/ChatRoom.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatListResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatRoomReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomWriteService.java
- src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteService.java
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/repository/ChatRoomRepositoryTest.java
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomReadServiceTest.java
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomWriteServiceTest.java
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomWriteServiceUnitTest.java
- 리뷰 요청 파라미터 matchId추가
- ChatRoom 엔티티 MatchId 필드 추가
- 채팅방 목록 조회 테스트
- 채팅방 생성 테스트
- 채팅방 생성 커스텀 예외처리
- 지원서 상세조회 MemberNickname 필드 추가
- 지원서 상세 조회 queryparam -> Pathvariable로 변경
- 
closes #198 
closes #200
> 채팅방 생성 오류 수정

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/Error.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GetEntity.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/MessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/S3Config.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/S3Uploader.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/domain/Dog.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/dto/DogReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/dto/DogRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/dto/DogUpdateReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/dog/repository/DogJpaRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- 유저 Profile ResponseDTO의 application 컬렉션의 필드에 title추가
close #199
> 유저 Profile Response DTO의  application 컬렉션 필드에 title 추가

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/BooleanToYNConverter.java
- src/main/java/com/kakaoseventeen/dogwalking/review/controller/ReviewController.java
- src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteService.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/controller/WalkController.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/domain/Walk.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- 종료되고, 리뷰가 작성되지 않은 산책을 반환하는 API 구현
- 리뷰 등록시 산책의 리뷰 여부를 true로 변경
close #202
> 종료되고, 리뷰가 작성되지 않은 산책을 반환하는 API 구현

- src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- WalkRepository findWalkNotEnd 쿼리 수정
close #202
> WalkRepository findWalkNotEnd 쿼리 수정

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ReviewMessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/review/ReviewMemberNotFoundException.java
- src/main/java/com/kakaoseventeen/dogwalking/review/controller/ReviewController.java
- src/main/java/com/kakaoseventeen/dogwalking/review/dto/GetReviewResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewReadService.java
- 리뷰 페이지 필요한 정보 조회 기능 구현
- 예외처리
close #203
> 리뷰 페이지에 필요한 정보 조회 기능 구현

- .idea/modules/dog-walking.main.iml
- src/main/java/com/kakaoseventeen/dogwalking/notification/domain/Notification.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/service/HomeService.java
- src/test/java/com/kakaoseventeen/dogwalking/notification/controller/NotificationControllerTest.java
- notification 쿼리수정 및 테이블 이름 수정, 테스트코드 추가
close #이슈번호
> Be 2 to weekly

- src/main/java/com/kakaoseventeen/dogwalking/application/controller/ApplicationController.java
- src/main/java/com/kakaoseventeen/dogwalking/application/dto/CreateAppReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationWriteService.java
- 지원서 API 수정 요구사항에 따른 스펙 변경
- 요청 데이터에 memberId 삭제
> 지원서 추가 요구사항 구현

- src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
- WalkRepository findWalkNotEnd 테이블 네임 소문자로 수정
- Notification -> notification
- Walk -> walk
close #202
> WalkRepository findWalkNotEnd 테이블 네임 소문자로 수정

- src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/domain/Walk.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkRespDTO.java
- src/main/resources/application-prod.yml
- WalkRepository findWalkNotEnd 필드 수정하기, NotificationJPRepository 쿼리 수정하기
close #202
> WalkRepository findWalkNotEnd 필드 수정하기, NotificationJPRepository 쿼리 수정하기

- src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
- WalkRepository notification_id 필드 수정하기
close #202
> WalkRepository notification_id 필드 수정하기

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/dummyData/PostConstructor.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/controller/ChatController.java
- src/main/java/com/kakaoseventeen/dogwalking/config/WebSocketConfig.java
- src/main/resources/static/css/main.css
- src/main/resources/static/index.html
- src/main/resources/static/js/main.js
- 채팅 기능 테스트용 데이터 추가
- 채팅 기능 테스트 코드
- 채팅 설정 웹소켓 endpoint 수정
close #213
> 채팅 기능 통합 테스트

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/dummyData/PostConstructor.java
> Member 제외한 더미 데이터 삭제

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/dummyData/PostConstructor.java
- 더미 데이터 Member password 8자 이상으로 수정
close #202
> 더미 데이터 Member password 8자 이상으로 수정

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/dummyData/PostConstructor.java
- 더미 데이터 Member password 8자 이상, 특수문자 포함으로 수정
close #202
> 더미 데이터 Member password 8자 이상, 특수문자 포함으로 수정

- src/main/java/com/kakaoseventeen/dogwalking/dog/controller/DogController.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
- walkRepository 쿼리 수정
- Not Equal에서 Equal로 수정
close #202
> walkRepository 쿼리 수정

- src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
- walkRepository 쿼리 equals  수정
close #202
> walkRepository 쿼리 equals  수정

- src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
- 기존 fetch join을 left join으로 변경 <- 변경 사유 : 여러 테이블을 join을 해야하는데, fetch join을 다중 사용시 참조 에러가 발생하기에
close #220
> notification 쿼리 수정

- src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/controller/WalkController.java
- Notification Repository 쿼리 수정하기
close #220
> UserProfile에 사용되는 Notification Repository 쿼리 Join절 수정

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/SecurityConfig.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/service/HomeService.java
> Be 2 to weekly - 시큐리티 수정, home service 리팩토링

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/JwtAuthenticationFilter.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/security/JwtProvider.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/security/SecurityConfig.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/MessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/service/NotificationService.java
> Be 2 to weekly - 9주차 코드리뷰 반영

- src/main/java/com/kakaoseventeen/dogwalking/review/controller/ReviewController.java
- src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteService.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- 종료되고, 리뷰가 작성되지 않은 산책 반환 API Spec 추가
close #226
> 종료되고, 리뷰가 작성되지 않은 산책 반환 API Spec 추가

- src/main/java/com/kakaoseventeen/dogwalking/config/WebSocketConfig.java
> Allowed Origin Pattern 수정

- src/main/java/com/kakaoseventeen/dogwalking/application/controller/ApplicationController.java
- src/main/java/com/kakaoseventeen/dogwalking/application/dto/GetAppMemberResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationReadService.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatListResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
- src/main/java/com/kakaoseventeen/dogwalking/review/controller/ReviewController.java
- src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewReadService.java
- 채팅기능 matchId추가
- 리뷰 조회 메서드 이름 변경
- 지원서 작성 전 조회 기능
close #223
> 채팅기능 matchId추가, 지원서 작성 전 조회 기능

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ApplicationMessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/application/ApplicationMemberNotFoundException.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/application/NotificationNotFoundException.java
- src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationWriteService.java
> 지원서 작성 커스텀 예외

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/SecurityConfig.java
> fix : cors 코드

- k8s/backend.yaml
- 배포 보안 설정
- 기능 요약1
close #이슈번호
> feat: backend secret config

- src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatListResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
- 채팅 목록 조회 서비스 분기점
- ChatListResDTO 필드 추가
> 채팅 목록 조회 분기점 생성

- src/main/java/com/kakaoseventeen/dogwalking/chat/controller/ChatController.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatMessageResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatMessageReadService.java
- 채팅 내역 조회 시간 필드 추가
- ChatMessageResDTO 필드 추가
> 채팅 내역 조회 시간 추가

- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
- 채팅 목록 memberId를 현재 로그인된 사용자 ID로 변경
> 채팅 목록 조회 응답 데이터 변경

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/MessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/notification/NotMyNotificationException.java
- src/main/java/com/kakaoseventeen/dogwalking/match/dto/MatchRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/match/service/MatchService.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/controller/InitController.java
- 매칭 리스트 응답 dto 수정, 커스텀 예외처리
close #이슈번호
> Be 2 to weekly - 매칭 리스트 응답 dto 수정, 커스텀 예외처리

- build.gradle
- k8s/backend.yaml
- k8s/configs/default.conf
- src/main/java/com/kakaoseventeen/dogwalking/_core/security/RestTemplateConfig.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/S3Config.java
- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- src/main/resources/application-cloudtype.yml
- src/main/resources/application-prod.yml
- AWS Proxy 설정
- 자세한 내용은 [노션](https://historical-blender-0ab.notion.site/14f2a7bb6cd24e42b2ef7627fa0fc202?pvs=4) 참고
close #250
> AWS Proxy 설정 추가

- src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- 패키지 구조 변경으로 인한 Exception 의존 에러 핸들링
close #250
> Exception 의존 에러 핸들링

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/RestTemplateConfig.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/S3Config.java
- 배포 환경이 둘로 나눠지면서 크램폴린, 클라우드타입에 따른 배포 Profile 분리 필요성 대두
- 이에 따라 크램폴린 설정 파일은 prod Profile
- 클라우드타입 설정 파일은 cloud Profile로 분기
close #250
> 크램폴린, 클라우드타입에 따른 배포 Profile 분리

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/JwtProvider.java
> Be 2 to weekly 리프레시 토큰 테스트

- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- MemberProfile 공고 수정
close #250
> MemberProfile 공고 수정

- src/main/resources/application-cloudtype.yml
- hibernate-diarect 방언 문제 해결
close #250
> hibernate-diarect 방언 문제 해결

- src/main/resources/application-cloud.yml
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- application.yml 수정 및 기본 profile prod로 변경
close #250
> application.yml 수정 및 기본 profile prod로 변경

- src/main/java/com/kakaoseventeen/dogwalking/dog/domain/Dog.java
- dog profile 수정 성별 필드 추가
close #250
> dog profile 수정 성별 필드 추가

- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- member Profile 공고 관련 수정
close #250
> member Profile 공고 관련 수정

- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- member Profile 공고 NPE 예외 핸들링
close #250
> member Profile 공고 NPE 예외 핸들링

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/SecurityConfig.java
> fix : 시큐리티 인가 수정

- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
- member Profile 쿼리 fetch join으로 수정
close #250
> member Profile 쿼리 fetch join으로 수정

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/JwtProvider.java
- 테스트 위한 토큰 발급시간 변경
close #이슈번호
> fix : 테스트 위한 토큰 발급시간 변경

- src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
- Member Profile 쿼리 수정
- 쿼리문에서 Null 체크 추가
close #250
> Member Profile 쿼리 수정

- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
- Profile Error 핸들링을 위한 로그 작성
close #250
> Profile Error 핸들링을 위한 로그 작성

- src/main/resources/application-cloud.yml
- ddl-auto 테이블 초기화를 위해서 create-drop으로 변경
close #250
> ddl-auto 테이블 초기화를 위해서 create-drop으로 변경

- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
> Profile 쿼리 수정

- src/main/java/com/kakaoseventeen/dogwalking/_core/security/JwtProvider.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/MemberProfileRespDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
- Profile 수정 코드 및 JWT AccessToken 시간 추가
close #250
> Profile 수정 코드 및 JWT AccessToken 시간 추가

- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ApplicationMessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ChatMessageCode.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/application/ApplicationNotFoundException.java
- src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/application/MatchNotFoundException.java
- src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationReadService.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/domain/ChatRoom.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/dto/MessageTypeDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatMessageWriteServiceImpl.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomWriteService.java
- src/main/java/com/kakaoseventeen/dogwalking/match/domain/Match.java
> 채팅방 생성 버그수정

- src/main/java/com/kakaoseventeen/dogwalking/chat/repository/ChatRoomRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
- src/main/resources/application-cloud.yml
> 채팅방 목록조회 버그 픽스

- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
> 채팅방 목록 조회 버그 픽스

- src/main/java/com/kakaoseventeen/dogwalking/walk/controller/WalkController.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- WalkStatus API 구현
close #288
> WalkStatus API 구현

- src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/controller/ChatRoomControllerTest.java
- src/test/java/com/kakaoseventeen/dogwalking/notification/controller/HomeControllerTest.java
- 사용하지 않는 import문 삭제
close #296
> 사용하지 않는 import문 삭제

- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
- src/main/java/com/kakaoseventeen/dogwalking/member/dto/request/UpdateProfileReqDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/payment/service/PaymentService.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/domain/Walk.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkResDTO.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
- src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
- src/main/java/com/kakaoseventeen/dogwalking/walkRoad/controller/WalkRoadController.java
> 산책시 산책 타입 반환

- src/main/java/com/kakaoseventeen/dogwalking/review/controller/ReviewController.java
- src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteService.java
- 견주가 리뷰 작성시 리뷰 True 등록
close #305
> 견주가 리뷰 작성시 리뷰 True 등록

- src/main/java/com/kakaoseventeen/dogwalking/chat/controller/ChatRoomController.java
- src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
- src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomReadServiceTest.java
- 채팅방 조회시 상대방 Id 반환
close #312
> 채팅방 조회시 상대방 Id 반환
